server:
  port: 10086
spring:
  application:
    name: simbrain-registry
  security:
    user:
      name: simbrain
      password: huowei
      roles: SERVICE_NODE
eureka:
  client:
    serviceUrl:
      defaultZone: http://simbrain:huowei@127.0.0.1:10086/eureka
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000
  instance:
    ip-address: true