server:
  port: 8081
spring:
  application:
    name: simbrain-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/young_volunteers?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: admin
  mail:
    username: 3111314916@qq.com
    password: gmpqfnygpvzxdgah
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
    default-encoding: UTF-8
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    ip-address: true
info:
  app.name: 毕业设计-NUC-huowei
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag
      logic-delete-value: 1 # 逻辑已删除
      logic-not-delete-value: 0 # 逻辑未删除
logging:
  pattern:
    file: "%msg%n"
  level:
      cn.simbrain.controller: info
  file:
    name: G:\logtest\logging.log
